name: Build Profanity Filter action image

on:
  push:
    branches:
      - main
    tags:
        - v*

jobs:
  publish:

    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v3
    - name: docker login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set container tag from branch
      if: github.ref_type == 'branch'
      run: echo "container_tag=latest"
      id: container_tag
    - name: Set container from tag
      if: github.ref_type == 'tag'
      run: echo "container_tag=${{ github.ref_name }}"
      id: tag
    - name: Publish app
      working-directory: ./src/ProfanityFilter.Action
      run: |
       dotnet publish 
            /t:PublishContainer \
            -r linux-musl-x64 \
            -p ContainerFamily=alpine3.18 \
            -p ContainerRegistry=ghcr.io \
            -p ContainerRepository=baronfel/profanity-filter \
            -p ContainerImageTag=${{ steps.container_tag.outputs.container_tag }} \
            -bl

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: msbuild.binlog
        path: src/ProfanityFilter.Action/msbuild.binlog
